const FEATURE_NAMES = [
  "ambulk",
  "amsend",
  "amverif",
  "anticolong",
  "ascii",
  "biner",
  "bitly",
  "breach",
  "bypass",
  "calc",
  "ccgen",
  "ceknamadana",
  "cekrek",
  "cekresi",
  "cekweb",
  "colongsw",
  "daftartiktok",
  "debiner",
  "ekspedisilist",
  "encode",
  "extra-tools",
  "facedetector",
  "fagsocial",
  "fakecam",
  "fakesw",
  "faketag",
  "fakevhs",
  "gh",
  "gmaps",
  "grammarly",
  "hapuswm",
  "hd5",
  "hd8",
  "hostmedia",
  "image",
  "timeis",
  "kirimpesangc",
  "mcstalk",
  "mikutalk",
  "morse",
  "bratspongebob",
  "cewekbrat",
  "cinematic",
  "codesnap",
  "fakebca",
  "fakech",
  "fakediscoard",
  "fakeff",
  "fakegroup",
  "fakegroupv2",
  "fakeigstory",
  "faketg",
  "faketiktok",
  "fakett",
  "faketweet",
  "hangingpolaroid",
  "xterm-maker-edit",
  "hotline",
  "iqc3",
  "iqc4",
  "fakeatm",
  "fakeff2",
  "fakeffduo",
  "fakeidcard",
  "fakeijin",
  "fakekarcis",
  "fakekartupelajar",
  "fakesertifikat",
  "fakesp",
  "faketiket",
  "ustadz",
  "drakememe",
  "fakeijazah",
  "jail",
  "patrickmeme",
  "quoteswindows",
  "fakepaspor",
  "addlimit",
  "banchat2",
  "banuser",
  "broadcast",
  "broadcastgc",
  "cheat",
  "clearsession",
  "deluser",
  "leavegc",
  "listbanchat",
  "cta_copy",
  "listown",
  "listpc",
  "listprem",
  "listsw",
  "antihidetag",
  "extra-admin",
  "groupstats",
  "audio-effect",
  "age-detection",
  "capcut",
  "gdrive",
  "blackjack"
];

const config = {
  name: 'newfit',
  alias: ['new'],
  category: 'main',
  description: 'Daftar 100 fitur baru',
  usage: '.newfit / .new',
  example: '.newfit',
  isOwner: false,
  isPremium: false,
  isGroup: false,
  isPrivate: false,
  cooldown: 2,
  energi: 0,
  isEnabled: true
};

async function handler(m) {
  const text = FEATURE_NAMES.map((name, i) => `${i + 1}. ${name}`).join('\n');
  return m.reply(text);
}

export { config, handler };
